# docker-compose.yml
version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
